version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: rabbitmq
    restart: always
    env_file:
      - ./SpotifyAPI/.rabbitmq-secrets
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  minio:
    image: minio/minio:latest
    hostname: minio
    restart: always
    command: server --console-address ":9001" /data
    volumes:
      - ~/apps/Spotify/minio-data:/data
    env_file:
      - ./SpotifyAPI/.minio-secrets
    ports:
      - "9000:9000"
      - "9001:9001"
volumes:
  cache:
    driver: local
    
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    volumes:
      - ~/apps/Spotify/mongo/data:/data/db
    ports:
      - "27017:27017"
