/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: src/userPage/userSubscription/protos/payment.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./payment_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.PaymentServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.PaymentServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SubscriptionUpdateData,
 *   !proto.ResultDto>}
 */
const methodDescriptor_PaymentService_UpdateSubscription = new grpc.web.MethodDescriptor(
  '/PaymentService/UpdateSubscription',
  grpc.web.MethodType.UNARY,
  proto.SubscriptionUpdateData,
  proto.ResultDto,
  /**
   * @param {!proto.SubscriptionUpdateData} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ResultDto.deserializeBinary
);


/**
 * @param {!proto.SubscriptionUpdateData} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ResultDto)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ResultDto>|undefined}
 *     The XHR Node Readable Stream
 */
proto.PaymentServiceClient.prototype.updateSubscription =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/PaymentService/UpdateSubscription',
      request,
      metadata || {},
      methodDescriptor_PaymentService_UpdateSubscription,
      callback);
};


/**
 * @param {!proto.SubscriptionUpdateData} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ResultDto>}
 *     Promise that resolves to the response
 */
proto.PaymentServicePromiseClient.prototype.updateSubscription =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/PaymentService/UpdateSubscription',
      request,
      metadata || {},
      methodDescriptor_PaymentService_UpdateSubscription);
};


module.exports = proto;

